# .github/workflows/helix-ivanovo.yml

name: helix-ivanovo

on:
  workflow_dispatch:

jobs:
  helix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install requests beautifulsoup4 openpyxl

      - run: mkdir -p output

      - run: python parser_helix.py

      - run: ls -lah output

      - uses: actions/upload-artifact@v4
        with:
          name: helix-csv
          path: output/helix_ivanovo.csv

      - uses: actions/upload-artifact@v4
        with:
          name: helix-xlsx
          path: output/helix_ivanovo.xlsx
